/**
 * Simple Java test for Soar SML SWIG bindings
 * This test verifies that the Java SWIG bindings can be loaded and basic operations work.
 */

// Import the SML classes (generated by SWIG) - they are in the default package
// import sml.Kernel;
// import sml.Agent;

public class SimpleJavaSMLTest {
    
    public static void main(String[] args) {
        boolean success = false;
        String errorMessage = "";
        
        try {
            System.out.println("Starting simple Java SML test...");
            
            // Test 1: Create kernel
            System.out.println("Creating Soar kernel...");
            Kernel kernel = Kernel.CreateKernelInCurrentThread();
            
            if (kernel == null) {
                throw new RuntimeException("Failed to create kernel - kernel is null");
            }
            
            if (kernel.HadError()) {
                throw new RuntimeException("Error creating kernel: " + kernel.GetLastErrorDescription());
            }
            
            System.out.println("[OK] Kernel created successfully");
            
            // Test 2: Get version
            String version = kernel.GetSoarKernelVersion();
            System.out.println("[OK] Soar version: " + version);
            
            // Test 3: Create agent
            System.out.println("Creating agent...");
            Agent agent = kernel.CreateAgent("test-agent");
            
            if (agent == null) {
                throw new RuntimeException("Failed to create agent - agent is null");
            }
            
            if (kernel.HadError()) {
                throw new RuntimeException("Error creating agent: " + kernel.GetLastErrorDescription());
            }
            
            System.out.println("[OK] Agent created successfully: " + agent.GetAgentName());
            
            // Test 4: Execute a simple command
            String result = agent.ExecuteCommandLine("echo Hello from Java!");
            System.out.println("[OK] Command executed: " + result.trim());
            
            // Test 5: Run a decision cycle
            agent.RunSelf(1);
            System.out.println("[OK] Ran one decision cycle");
            
            // Cleanup
            kernel.DestroyAgent(agent);
            kernel.Shutdown();
            System.out.println("[OK] Cleanup completed");
            
            success = true;
            System.out.println("\nSUCCESS: All tests passed! Java SWIG bindings are working correctly.");
            
        } catch (UnsatisfiedLinkError e) {
            errorMessage = "Failed to load native library: " + e.getMessage();
            System.err.println("[ERROR] " + errorMessage);
            e.printStackTrace();
        } catch (Exception e) {
            errorMessage = "Test failed: " + e.getMessage();
            System.err.println("[ERROR] " + errorMessage);
            e.printStackTrace();
        }
        
        // Exit with appropriate code
        if (success) {
            System.exit(0);
        } else {
            System.err.println("\nFAILED: Java SML test failed: " + errorMessage);
            System.exit(1);
        }
    }
}